#!   /usr/bin/env   python
# -*- coding: utf-8 -*
'''
Tool to update the gateware in the SPIflash using etherbone/serial communication

@file
@date Created on Jun 16, 2015
@author Benoit Rat (benoit<AT>sevensols.com)
@copyright LGPL v2.1
@see http://www.ohwr.org
@see http://www.sevensols.com
'''

import sys
import traceback
import os
import re
import subprocess
from optparse import OptionParser

sys.path.append('../../')

from pts_core.bridges.ethbone import *
#from pts_core.bridges.wb_uart import *
from pts_core.main.ptsexcept import *
from pts_core.main.ptslogger import PTSLogger
from pts_core.main.tools import KeyInput


def main():

    use = "Usage: %prog [--bus=uart --lun=0 --debug] mscfile"
    parser = OptionParser(usage=use, version="spiflash update v1.0")

    parser.add_option("-l", "--lun", help="Logical unit Number (SerialPort / IP)", dest="lun")
    parser.add_option("-b", "--bus", help="Bus UART/EB", dest="bus_type", default="EB")
    parser.add_option("-d", "--debug", help="Debug Option", dest="debug", default=False, action="store_true")

    options, args = parser.parse_args()

    ## Opening Bus connection
    try:
        if options.bus_type.lower() == "eb":
            bus = EthBone(options.lun,options.debug)
        #else: ##options.bus_type == "UART"
           # bus = wb_UART()
            #bus.open(options.lun)
    except BusException, e:
        print "Fatal:BUS Exception: %s" % (e)


    ##Check SDB (TO BE DONE!)

    ##Check Endpoint Register
    bus.test_rw()

    ##Check block read/write using MiniNIC RAM.
    bus.test_rwblock(0x2000)



    ##Open File


    ## Loop on 256 packets






def EB_upload(f):

    print "Just a test"




if __name__ == '__main__':
    main()