#!   /usr/bin/env   python
# -*- coding: utf-8 -*
'''
Tool to update the gateware in the SPIflash using etherbone/serial communication

For example if you want to flash a new GW for the LEN with IP 192.168.7.50 you will
need to write something like:

    ./spiflash_update --bus=EB --lun=udp/192.168.7.54 --mode=update --file=wr-len-v2.x.mcs


@file
@date Created on Jun 16, 2015
@author Benoit Rat (benoit<AT>sevensols.com)
@author Husein Gomiz (hgomiz<AT>sevensols.com)
@copyright LGPL v2.1
@see http://www.ohwr.org
@see http://www.sevensols.com
'''

import sys
import traceback
import os
import re
import subprocess
from optparse import OptionParser


sys.path.append('../../')

from py7slib.bridges.ethbone import *
#from bridges.wb_uart import *
from main.ptsexcept import *
from main.ptslogger import PTSLogger
from py7slib.tools import KeyInput
from pts_core.periph.ipc_spiflash import *


def main():

    use = "Usage: %prog [--bus=uart --lun=0 --debug -file=mcsfile] "
    parser = OptionParser(usage=use, version="spiflash update v1.0")

    parser.add_option("-l", "--lun", help="Logical unit Number (SerialPort / IP)", dest="lun")
    parser.add_option("-b", "--bus", help="Bus UART/EB", dest="bus_type", default="EB")
    parser.add_option("-d", "--debug", help="Debug Flag", dest="debug", default=False, action="store_true")
    parser.add_option("-s", "--silent", help="Silent Flag", dest="silent", default=False, action="store_true")
    parser.add_option("-m", "--mode", help="cido: Check ID Only," "vo: Verify Only," "update: update flash image", dest="mode", default="cido")
    parser.add_option("-f", "--file", help="MCS file", dest="file")

    options, args = parser.parse_args()

    ## Opening Bus connection
    try:
        if options.bus_type.lower() == "eb":
            bus = EthBone(options.lun,(options.mode=="test"))
            bus.silent=options.silent
        #else: ##options.bus_type == "UART"
           # bus = wb_UART()
            #bus.open(options.lun)
    except BusException, e:
        print "Fatal: %s" % (e)
        return 1

    #TODO: Check SDB to get the base address of the cores

    if options.mode=="test":
        ##Check Endpoint Register
        bus.test_rw()

        ##Check block read/write using MiniNIC RAM.
        bus.test_rwblock(0x20000)
        return 0

    # This address must be changed if the layout changes.
    flash=SpiFlash(bus,0x40000,options.debug)

    flash.flash_update(options.mode,options.file)



if __name__ == '__main__':
    main()
